export const profile = {
  name:      'Aditya Prabhudessai',
  firstName: 'Aditya',
  lastName:  'Prabhudessai',
  role:      'AI/ML Engineer & Full Stack Developer',
  tagline:   'Final-year engineer. AI systems, developer tools, products that ship.',
  location:  'Goa, India',
  education: 'B.Tech Information Technology · Manipal University Jaipur · 2026',
  status:    'Available for opportunities',
  email:     'adiprabhu04@gmail.com',
  github:    'https://github.com/adiprabhu04',
  linkedin:  'https://linkedin.com/in/adityaprabhudessai',
  resume:    'https://drive.google.com/file/d/1OlQgQEoDd5O0NFO_GWEP92grlUJHIfqE/view?usp=sharing',
  stats: [
    { value: '4',   label: 'Projects\nShipped' },
    { value: '4',   label: 'Internships\nCompleted' },
    { value: '1M+', label: 'Records\nProcessed' },
  ],
}

export const projects = [
  {
    id:       'jot-it',
    num:      '01',
    name:     'Jot It',
    category: 'Full Stack · AI',
    year:     '2026',
    tags:     ['ASP.NET Core 8', 'FastAPI', 'React Native', 'Azure CV', 'PostgreSQL', 'Docker'],
    headline: 'OCR as infrastructure, not a demo.',
    body:     'Full-stack note-taking with handwriting recognition built across three services. Azure Computer Vision returns per-word confidence scores; the result lands in a structured note. ASP.NET Core 8 API, Python FastAPI OCR microservice, and a React Native + Expo client. JWT auth, PostgreSQL, ships as an installable PWA.',
    impact:   'Deployed to production at Persistent Systems. Real offline caching, real auth, real multi-service architecture.',
    github:   null,
    live:     'https://persistent-ai-ml-internship.onrender.com',
  },
  {
    id:       'structiq',
    num:      '02',
    name:     'StructIQ',
    category: 'AI · RAG',
    year:     '2025',
    tags:     ['LangChain', 'ChromaDB', 'Groq Llama 3.1', 'RAG', 'Streamlit', 'Google Sheets'],
    headline: 'RAG for a real client, not a tutorial.',
    body:     'Domain-specific AI consultant for a structural engineering firm. Covers property valuations, RCC design, structural audits, and legal advisory without hallucinating. RAG pipeline over 100+ curated Q&A pairs, ChromaDB for retrieval, Groq Llama 3.1 for inference. Leads captured automatically to Google Sheets.',
    impact:   'Deployed for a real client. 100+ domain Q&A pairs indexed. Automated lead pipeline in production.',
    github:   'https://github.com/adiprabhu04/AI-Chatbot',
    live:     null,
  },
  {
    id:       'audiencelens',
    num:      '03',
    name:     'AudienceLens',
    category: 'NLP · ML',
    year:     '2025',
    tags:     ['BERT', 'DeBERTa', 'Clustering', 'NLP', 'Python'],
    headline: 'Not just sentiment — who\'s doing the feeling, and why.',
    body:     'Pulls a YouTube video\'s comment section and maps where opinion lands. BERT and DeBERTa handle sentiment classification; clustering surfaces recurring audience personas. The output tells you not just how people feel, but which distinct groups feel that way.',
    impact:   'Large-scale comment intelligence — sentiment plus audience persona mapping from raw text at volume.',
    github:   'https://github.com/adiprabhu04/sentiment-youtube-bert',
    live:     null,
  },
  {
    id:       'xplainnews',
    num:      '04',
    name:     'XplainNews',
    category: 'ML · XAI',
    year:     '2025',
    tags:     ['LSTM', 'SHAP', 'LIME', 'TF-IDF', 'NLP', 'Scikit-learn'],
    headline: 'A classifier that shows its work.',
    body:     'LSTM-based fake news detector with SHAP and LIME plugged in so you can see which phrases drove the prediction. The point was never just accuracy — it was understanding where the model is wrong and why, through systematic error analysis on misclassified samples.',
    impact:   'Interpretability-first NLP — the model\'s reasoning surfaced and auditable, not hidden behind a number.',
    github:   'https://github.com/adiprabhu04/fake-news-detection',
    live:     null,
  },
]

export const experience = [
  {
    company: 'Persistent Systems',
    role:    'Software Developer Intern',
    period:  'Jan 2026 — Present',
    current: true,
    desc:    'Building Jot It — a three-service AI note-taking app with handwriting OCR, React Native mobile client, ASP.NET Core 8 API, FastAPI OCR microservice, PostgreSQL, and a PWA shell. JWT auth, Docker deployment.',
    tags:    ['FastAPI', 'ASP.NET Core', 'React Native', 'Azure CV'],
  },
  {
    company: 'Smart Mieten Tech',
    role:    'AI/ML Intern',
    period:  'Jul 2025 — Aug 2025',
    current: false,
    desc:    'Forecasting models on 1M+ time-series insurance records. Statistical and temporal feature engineering improved prediction accuracy by 15%. Pipeline optimizations cut training time by 20%.',
    tags:    ['Python', 'Pandas', 'Time Series', 'ML'],
  },
  {
    company: 'Skill Craft Technology',
    role:    'Machine Learning Intern',
    period:  'Jun 2025 — Jul 2025',
    current: false,
    desc:    'End-to-end ML pipelines with cross-validation, improving model robustness by 12%. Contributed to an internal LLM monitoring dashboard tracking drift, latency, and output quality.',
    tags:    ['ML Ops', 'LLM', 'Python'],
  },
  {
    company: 'Unified Mentor',
    role:    'Data Analyst Intern',
    period:  'Feb 2025 — Mar 2025',
    current: false,
    desc:    'Automated ETL workflows and BI dashboards, cutting manual reporting effort by 40%. Analyzed 500k+ row datasets and produced structured reports for non-technical stakeholders.',
    tags:    ['ETL', 'Power BI', 'SQL'],
  },
]

export const tools = [
  { category: 'Languages',  items: ['Python', 'TypeScript', 'JavaScript', 'C++', 'Java'] },
  { category: 'AI / ML',    items: ['PyTorch', 'TensorFlow', 'LangChain', 'Scikit-learn', 'SHAP', 'LIME', 'BERT'] },
  { category: 'Interface',  items: ['React', 'Next.js', 'Tailwind CSS', 'Framer Motion', 'React Native'] },
  { category: 'Backend',    items: ['FastAPI', 'ASP.NET Core', 'Node.js', 'REST', 'JWT'] },
  { category: 'Data',       items: ['Pandas', 'NumPy', 'Matplotlib', 'Seaborn', 'Power BI', 'Tableau'] },
  { category: 'Storage',    items: ['PostgreSQL', 'MongoDB', 'MySQL', 'ChromaDB', 'FAISS'] },
  { category: 'Infra',      items: ['Docker', 'AWS', 'GCP', 'Azure', 'GitHub Actions'] },
  { category: 'Studying',   items: ['Distributed inference', 'LLM fine-tuning', 'Vector retrieval at scale'] },
]
